version: '3'
services:
  db:
    container_name: postgres-db
    image: postgres:15
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data

  api:
    image: python:3.10-alpine
    container_name: import-csv-api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - '${API_PORT}:8000'
    depends_on:
      - db
    env_file:
      - ./.env
    entrypoint: /app/entrypoint.sh
    command: pipenv run manage runserver 0.0.0.0:8000

  web:
    image: node:20-alpine
    working_dir: /app
    depends_on:
      - api
    env_file:
      - ./.env
    volumes:
      - ./web:/app
    ports:
      - '${WEB_PORT}:3000' # out:in
    command: sh -c "npm install -g pnpm && pnpm install && pnpm build && pnpm start"
