version: '3'
services:
  db:
    container_name: postgres-db
    image: postgres:15
    env_file:
      - ./api/project/.env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: python:3.10-alpine
    container_name: import-csv-api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./api/project/.env
    entrypoint: /app/entrypoint.sh
    command: pipenv run manage runserver 0.0.0.0:8000

  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - '3000:3000' # out:in
    command: sh -c "npm install -g pnpm && pnpm install && pnpm build && pnpm start"

volumes:
  db_data:
