version: '3'
services:
  db:
    container_name: postgres-db
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    network_mode: "host"


  api:
    image: python:3.10.15-alpine
    container_name: import-csv-api
    working_dir: /app
    volumes:
      - ./api:/app
    depends_on:
      - db
    env_file:
      - ./.env
    entrypoint: /app/entrypoint.sh
    command: pipenv run manage runserver 0.0.0.0:8000
    network_mode: "host"

  web:
    image: node:20-alpine
    working_dir: /app
    depends_on:
      - api
    env_file:
      - ./.env
    volumes:
      - ./web:/app
    command: sh -c "npm install -g pnpm && pnpm install && pnpm build && pnpm start"
    network_mode: "host"

