
version: '3'
services:
  db:
    container_name: postgres-db
    image: postgres:15-alpine
    env_file:
      - ./api-server/project/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./web-client:/app
    ports:
      - "3000:3000" # out:in
    command: sh -c "npm install -g pnpm && pnpm install && pnpm build && pnpm start"
      
volumes:
  db_data:
