# Generated by Django 5.1.1 on 2024-09-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_csvimport_unique_import_id_for_client_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csvdata",
            old_name="import_id",
            new_name="import_name",
        ),
    ]
