version: '3'
services:
  db:
    container_name: postgres-db
    image: postgres:15-alpine
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  db_data:
    