version: '3'
services:
  db:
    container_name: postgres-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: import-csv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Br@@5up3r
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data:
    