# Generated by Django 5.1.1 on 2024-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="csvimport",
            name="unique_import_id_for_client",
        ),
        migrations.RemoveField(
            model_name="csvimport",
            name="id",
        ),
        migrations.AddField(
            model_name="csvimport",
            name="import_name",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="csvimport",
            name="import_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
